<?php

namespace ContainerN2iZx5P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LE8AC5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LE8AC_5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LE8AC_5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'voypersonalise' => ['privates', '.errored..service_locator.LE8AC_5.App\\Entity\\Voypersonalise', NULL, 'Cannot autowire service ".service_locator.LE8AC_5": it needs an instance of "App\\Entity\\Voypersonalise" but this type has been excluded in "config/services.yaml".'],
        ], [
            'voypersonalise' => 'App\\Entity\\Voypersonalise',
        ]);
    }
}
