<?php

namespace ContainerN2iZx5P;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRes2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.MQl1vAe.App\Entity\Res' shared service.
     *
     * @return \App\Entity\Res
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.MQl1vAe": it needs an instance of "App\\Entity\\Res" but this type has been excluded in "config/services.yaml".');
    }
}
