<?php

namespace ContainerUMtxBqg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZkadRX2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zkadRX2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zkadRX2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'resRepository' => ['privates', 'App\\Repository\\ResRepository', 'getResRepositoryService', true],
        ], [
            'resRepository' => 'App\\Repository\\ResRepository',
        ]);
    }
}
