<?php

namespace ContainerUMtxBqg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProgrammeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Xvt.gnO.App\Entity\Programme' shared service.
     *
     * @return \App\Entity\Programme
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Xvt.gnO": it needs an instance of "App\\Entity\\Programme" but this type has been excluded in "config/services.yaml".');
    }
}
