<?php

namespace ContainerUMtxBqg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVoypersonaliseService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5QM8HVE.App\Entity\Voypersonalise' shared service.
     *
     * @return \App\Entity\Voypersonalise
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.5QM8HVE": it needs an instance of "App\\Entity\\Voypersonalise" but this type has been excluded in "config/services.yaml".');
    }
}
